spring:
  datasource:
    url: 'jdbc:h2:file:/data/database/h2'
    username: sa
    password: null
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirH2Dialect
      hibernate.search.enabled: false

hapi:
  fhir:
    fhir_version: R4
